const express=require('express')
const router=express.Router()
const movimientosController=require('../controllers/movimientos.controller')
const {validateInputMovimiento}=require('../middlewares/movimientos-validator')
router.get('/',movimientosController.obtenerTodas)
router.get('/usuario/:usuario_id',movimientosController.obtenerPorUsuario)
router.get('/categoria/:categoria_id',movimientosController.obtenerPorCategoria)
router.get('/:id',movimientosController.obtenerPorId)
router.post('/',validateInputMovimiento,movimientosController.crear)
router.put('/:id',validateInputMovimiento,movimientosController.actualizar)
router.delete('/:id',movimientosController.eliminar)
module.exports=router