const express=require('express')
const router=express.Router()
const usuariosController=require('../controllers/usuarios.controller')
const {validateInputUsuario}=require('../middlewares/usuarios-validator')
const { verificarToken } = require('../middlewares/auth.middleware')
router.get('/',verificarToken, usuariosController.obtenerTodas)
router.get('/:id',verificarToken, usuariosController.obtenerPorId)
router.post('/',verificarToken, validateInputUsuario,usuariosController.crear)
router.put('/:id',verificarToken, validateInputUsuario,usuariosController.actualizar)
router.delete('/:id',verificarToken, usuariosController.eliminar)
module.exports=router